var searchData=
[
  ['data_0',['data',['../library-design.html#autotoc_md15',1,'Inheriting classes with private data'],['../library-design.html#autotoc_md14',1,'Use of class-specific structs to hold data.']]],
  ['debugging_1',['Internal Debugging',['../internal-debugging.html',1,'usage-overview']]],
  ['default_2',['Why doesn&apos;t Log4cxx use buffered asynchronous output by default?',['../faq.html#buffered_output',1,'']]],
  ['default_20cmake_20option_20values_3',['Default CMake option values',['../dependencies.html#autotoc_md7',1,'']]],
  ['default_20initialization_20behaviour_4',['Default Initialization Behaviour',['../configuration-files.html#default-initialization',1,'']]],
  ['dependencies_5',['Dependencies',['../dependencies.html',1,'Log4cxx Dependencies'],['../dependencies.html#autotoc_md6',1,'Optional Dependencies']]],
  ['dependencies_20only_6',['Licenses(direct dependencies only)',['../dependencies.html#autotoc_md9',1,'']]],
  ['deprecated_20list_7',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20notes_8',['Library Design Notes',['../library-design.html',1,'development-overview']]],
  ['detected_20by_20oss_20fuzz_9',['detected by OSS Fuzz',['../fuzzing.html#reproduce',1,'Reproducing fuzzing failures detected by OSS-Fuzz'],['../fuzzing.html#view',1,'Viewing fuzzing failures detected by OSS-Fuzz']]],
  ['develop_10',['Develop',['../development-overview.html',1,'']]],
  ['direct_20dependencies_20only_11',['Licenses(direct dependencies only)',['../dependencies.html#autotoc_md9',1,'']]],
  ['disabling_20console_20color_12',['Disabling Console Color',['../disabling-color.html',1,'usage-overview']]],
  ['dll_13',['Building log4cxx.dll',['../build-vcpkg.html#autotoc_md2',1,'']]],
  ['do_20i_20add_20a_20custom_20level_20to_20apache_20log4cxx_14',['How do I add a custom level to Apache Log4cxx?',['../faq.html#custom_levels',1,'']]],
  ['do_20i_20use_20log4cxx_20with_20cmake_15',['How do I use Log4cxx with CMake?',['../buildsystems.html#use_with_cmake',1,'']]],
  ['do_20i_20use_20log4cxx_20with_20cmake_20and_20pkg_20config_16',['How do I use Log4cxx with CMake and pkg-config?',['../buildsystems.html#use_with_cmake_pkgconfig',1,'']]],
  ['do_20i_20use_20log4cxx_20with_20plain_20make_17',['How do I use Log4cxx with plain Make?',['../buildsystems.html#use_with_make',1,'']]],
  ['do_20i_20use_20log4cxx_20with_20qmake_18',['How do I use Log4cxx with QMake?',['../buildsystems.html#use_with_qmake',1,'']]],
  ['does_20apache_20log4cxx_20support_20unicode_19',['Does Apache Log4cxx support Unicode?',['../faq.html#unicode_supported',1,'']]],
  ['does_20log4cxx_20support_20logging_20at_20process_20termination_20',['Does Log4cxx support logging at process termination?',['../faq.html#atexit_events',1,'']]],
  ['doesn_20t_20log4cxx_20use_20buffered_20asynchronous_20output_20by_20default_21',['Why doesn&apos;t Log4cxx use buffered asynchronous output by default?',['../faq.html#buffered_output',1,'']]],
  ['download_22',['Download',['../download.html',1,'get']]],
  ['download_20apache_20log4cxx_201_208_200_23',['Download Apache Log4cxx 1.8.0',['../download.html#autotoc_md23',1,'']]]
];
