var searchData=
[
  ['a_20custom_20level_20to_20apache_20log4cxx_0',['How do I add a custom level to Apache Log4cxx?',['../faq.html#custom_levels',1,'']]],
  ['a_20less_20simple_20example_1',['A Less Simple Example',['../quick-start.html#example2',1,'']]],
  ['a_20logger_20to_20use_20asynchronous_20output_2',['Configuring a logger to use asynchronous output',['../configuration-files.html#asynch-output',1,'']]],
  ['a_20note_20on_20c_20version_20and_20boost_3',['A note on C++ version and Boost',['../dependencies.html#autotoc_md8',1,'']]],
  ['a_20security_20issue_4',['Reporting a security issue',['../community.html#security',1,'']]],
  ['a_20simple_20example_5',['A Simple Example',['../quick-start.html#example1',1,'']]],
  ['access_6',['Web Access',['../source-repository.html#autotoc_md11',1,'']]],
  ['access_7',['Anonymous access',['../source-repository.html#autotoc_md12',1,'']]],
  ['add_20a_20custom_20level_20to_20apache_20log4cxx_8',['How do I add a custom level to Apache Log4cxx?',['../faq.html#custom_levels',1,'']]],
  ['additivity_9',['Additivity',['../concepts.html#appender-additivity',1,'']]],
  ['also_10',['See Also',['../library-design.html#autotoc_md17',1,'']]],
  ['and_20boost_11',['A note on C++ version and Boost',['../dependencies.html#autotoc_md8',1,'']]],
  ['and_20layouts_12',['Loggers, Appenders and Layouts',['../concepts.html',1,'usage-overview']]],
  ['and_20pkg_20config_13',['How do I use Log4cxx with CMake and pkg-config?',['../buildsystems.html#use_with_cmake_pkgconfig',1,'']]],
  ['anonymous_20access_14',['Anonymous access',['../source-repository.html#autotoc_md12',1,'']]],
  ['apache_20log4cxx_15',['How do I add a custom level to Apache Log4cxx?',['../faq.html#custom_levels',1,'']]],
  ['apache_20log4cxx_201_208_200_16',['Download Apache Log4cxx 1.8.0',['../download.html#autotoc_md23',1,'']]],
  ['apache_20log4cxx_20support_20unicode_17',['Does Apache Log4cxx support Unicode?',['../faq.html#unicode_supported',1,'']]],
  ['appenders_18',['Appenders',['../concepts.html#appenders',1,'']]],
  ['appenders_20and_20layouts_19',['Loggers, Appenders and Layouts',['../concepts.html',1,'usage-overview']]],
  ['application_20on_20windows_20crashes_20on_20shutdown_20',['My application on Windows crashes on shutdown?',['../faq.html#msvc_crash',1,'']]],
  ['apr_20apr_20util_21',['APR+APR-Util',['../dependencies.html#autotoc_md3',1,'']]],
  ['apr_20util_22',['APR+APR-Util',['../dependencies.html#autotoc_md3',1,'']]],
  ['asked_20technical_20questions_23',['Frequently Asked Technical Questions',['../faq.html',1,'usage-overview']]],
  ['asynchronous_20output_24',['Configuring a logger to use asynchronous output',['../configuration-files.html#asynch-output',1,'']]],
  ['asynchronous_20output_20by_20default_25',['Why doesn&apos;t Log4cxx use buffered asynchronous output by default?',['../faq.html#buffered_output',1,'']]],
  ['at_20process_20termination_26',['Does Log4cxx support logging at process termination?',['../faq.html#atexit_events',1,'']]]
];
