var searchData=
[
  ['samples_0',['Configuration Samples',['../configuration-files.html#configuration-samples',1,'']]],
  ['security_20issue_1',['Reporting a security issue',['../community.html#security',1,'']]],
  ['sed_20gzip_20zip_2',['sed+gzip+zip',['../dependencies.html#autotoc_md4',1,'']]],
  ['see_20also_3',['See Also',['../library-design.html#autotoc_md17',1,'']]],
  ['selection_20rule_4',['Basic Selection Rule',['../concepts.html#selection-rule',1,'']]],
  ['shutdown_5',['My application on Windows crashes on shutdown?',['../faq.html#msvc_crash',1,'']]],
  ['signal_20handling_20with_20log4cxx_6',['Signal Handling with Log4cxx',['../threading.html#signal-handling',1,'']]],
  ['simple_20example_7',['Simple Example',['../quick-start.html#example2',1,'A Less Simple Example'],['../quick-start.html#example1',1,'A Simple Example']]],
  ['source_20repository_8',['Source Repository',['../source-repository.html',1,'development-overview']]],
  ['specific_20structs_20to_20hold_20data_9',['Use of class-specific structs to hold data.',['../library-design.html#autotoc_md14',1,'']]],
  ['stacktrace_20into_20the_20mdc_10',['Putting the stacktrace into the MDC',['../stacktrace-support.html#autotoc_md20',1,'']]],
  ['stacktrace_20support_11',['Stacktrace Support',['../stacktrace-support.html',1,'usage-overview']]],
  ['start_12',['Quick Start',['../quick-start.html',1,'usage-overview']]],
  ['std_3a_3aformat_20instead_20of_20fmt_3a_3aformat_13',['Using std::format instead of fmt::format',['../dependencies.html#autotoc_md5',1,'']]],
  ['structs_20to_20hold_20data_14',['Use of class-specific structs to hold data.',['../library-design.html#autotoc_md14',1,'']]],
  ['style_20requests_15',['Using {fmt} style requests',['../concepts.html#logging-with-fmt',1,'']]],
  ['support_16',['Support',['../qt-support.html',1,'Qt Support'],['../stacktrace-support.html',1,'Stacktrace Support']]],
  ['support_20logging_20at_20process_20termination_17',['Does Log4cxx support logging at process termination?',['../faq.html#atexit_events',1,'']]],
  ['support_20unicode_18',['Does Apache Log4cxx support Unicode?',['../faq.html#unicode_supported',1,'']]],
  ['supported_20options_19',['Supported options',['../build-cmake.html#autotoc_md21',1,'']]],
  ['system_20',['Usage with your build system',['../buildsystems.html',1,'usage-overview']]],
  ['systems_21',['Unix type systems',['../build-cmake.html#Linux',1,'']]]
];
