var searchData=
[
  ['c_20version_20and_20boost_0',['A note on C++ version and Boost',['../dependencies.html#autotoc_md8',1,'']]],
  ['change_20log_1',['Change Log',['../changelog.html',1,'get']]],
  ['class_20specific_20structs_20to_20hold_20data_2',['Use of class-specific structs to hold data.',['../library-design.html#autotoc_md14',1,'']]],
  ['classes_20with_20private_20data_3',['Inheriting classes with private data',['../library-design.html#autotoc_md15',1,'']]],
  ['cmake_4',['CMake',['../build-cmake.html',1,'Building with CMake'],['../buildsystems.html#use_with_cmake',1,'How do I use Log4cxx with CMake?']]],
  ['cmake_20and_20pkg_20config_5',['How do I use Log4cxx with CMake and pkg-config?',['../buildsystems.html#use_with_cmake_pkgconfig',1,'']]],
  ['cmake_20option_20values_6',['Default CMake option values',['../dependencies.html#autotoc_md7',1,'']]],
  ['color_7',['Disabling Console Color',['../disabling-color.html',1,'usage-overview']]],
  ['community_8',['Community',['../community.html',1,'']]],
  ['conclusions_9',['Conclusions',['../conclusions.html',1,'usage-overview']]],
  ['config_10',['How do I use Log4cxx with CMake and pkg-config?',['../buildsystems.html#use_with_cmake_pkgconfig',1,'']]],
  ['configurable_20properties_11',['Configurable properties',['../classlog4cxx_1_1AsyncAppender.html#autotoc_md0',1,'']]],
  ['configuration_12',['Configuration',['../quick-start.html#configuration',1,'Runtime Configuration'],['../filters.html#configure-filter',1,'Runtime Configuration']]],
  ['configuration_20files_13',['Configuration Files',['../configuration-files.html',1,'usage-overview']]],
  ['configuration_20samples_14',['Configuration Samples',['../configuration-files.html#configuration-samples',1,'']]],
  ['configuring_20a_20logger_20to_20use_20asynchronous_20output_15',['Configuring a logger to use asynchronous output',['../configuration-files.html#asynch-output',1,'']]],
  ['configuring_20thread_16',['Configuring Thread',['../threading.html#configuring',1,'']]],
  ['console_20color_17',['Disabling Console Color',['../disabling-color.html',1,'usage-overview']]],
  ['coverage_18',['Testing coverage',['../supported-systems.html',1,'build']]],
  ['crashes_20on_20shutdown_19',['My application on Windows crashes on shutdown?',['../faq.html#msvc_crash',1,'']]],
  ['custom_20level_20to_20apache_20log4cxx_20',['How do I add a custom level to Apache Log4cxx?',['../faq.html#custom_levels',1,'']]],
  ['custom_20types_21',['Logging Custom Types',['../concepts.html#custom-types',1,'']]]
];
