var annotated_dup =
[
    [ "log4cxx", "namespacelog4cxx.html", [
      [ "config", "namespacelog4cxx_1_1config.html", [
        [ "PropertySetter", "classlog4cxx_1_1config_1_1PropertySetter.html", "classlog4cxx_1_1config_1_1PropertySetter" ]
      ] ],
      [ "db", "namespacelog4cxx_1_1db.html", [
        [ "DBAppender", "classlog4cxx_1_1db_1_1DBAppender.html", "classlog4cxx_1_1db_1_1DBAppender" ],
        [ "ODBCAppender", "classlog4cxx_1_1db_1_1ODBCAppender.html", "classlog4cxx_1_1db_1_1ODBCAppender" ],
        [ "SQLException", "classlog4cxx_1_1db_1_1SQLException.html", "classlog4cxx_1_1db_1_1SQLException" ]
      ] ],
      [ "filter", "namespacelog4cxx_1_1filter.html", [
        [ "AndFilter", "classlog4cxx_1_1filter_1_1AndFilter.html", "classlog4cxx_1_1filter_1_1AndFilter" ],
        [ "DenyAllFilter", "classlog4cxx_1_1filter_1_1DenyAllFilter.html", "classlog4cxx_1_1filter_1_1DenyAllFilter" ],
        [ "ExpressionFilter", "classlog4cxx_1_1filter_1_1ExpressionFilter.html", "classlog4cxx_1_1filter_1_1ExpressionFilter" ],
        [ "LevelMatchFilter", "classlog4cxx_1_1filter_1_1LevelMatchFilter.html", "classlog4cxx_1_1filter_1_1LevelMatchFilter" ],
        [ "LevelRangeFilter", "classlog4cxx_1_1filter_1_1LevelRangeFilter.html", "classlog4cxx_1_1filter_1_1LevelRangeFilter" ],
        [ "LocationInfoFilter", "classlog4cxx_1_1filter_1_1LocationInfoFilter.html", "classlog4cxx_1_1filter_1_1LocationInfoFilter" ],
        [ "LoggerMatchFilter", "classlog4cxx_1_1filter_1_1LoggerMatchFilter.html", "classlog4cxx_1_1filter_1_1LoggerMatchFilter" ],
        [ "MapFilter", "classlog4cxx_1_1filter_1_1MapFilter.html", "classlog4cxx_1_1filter_1_1MapFilter" ],
        [ "PropertyFilter", "classlog4cxx_1_1filter_1_1PropertyFilter.html", "classlog4cxx_1_1filter_1_1PropertyFilter" ],
        [ "StringMatchFilter", "classlog4cxx_1_1filter_1_1StringMatchFilter.html", "classlog4cxx_1_1filter_1_1StringMatchFilter" ]
      ] ],
      [ "helpers", "namespacelog4cxx_1_1helpers.html", [
        [ "AbsoluteTimeDateFormat", "classlog4cxx_1_1helpers_1_1AbsoluteTimeDateFormat.html", "classlog4cxx_1_1helpers_1_1AbsoluteTimeDateFormat" ],
        [ "AppenderAttachableImpl", "classlog4cxx_1_1helpers_1_1AppenderAttachableImpl.html", "classlog4cxx_1_1helpers_1_1AppenderAttachableImpl" ],
        [ "APRInitializer", "classlog4cxx_1_1helpers_1_1APRInitializer.html", "classlog4cxx_1_1helpers_1_1APRInitializer" ],
        [ "BindException", "classlog4cxx_1_1helpers_1_1BindException.html", "classlog4cxx_1_1helpers_1_1BindException" ],
        [ "BufferedWriter", "classlog4cxx_1_1helpers_1_1BufferedWriter.html", "classlog4cxx_1_1helpers_1_1BufferedWriter" ],
        [ "ByteArrayInputStream", "classlog4cxx_1_1helpers_1_1ByteArrayInputStream.html", "classlog4cxx_1_1helpers_1_1ByteArrayInputStream" ],
        [ "ByteArrayOutputStream", "classlog4cxx_1_1helpers_1_1ByteArrayOutputStream.html", "classlog4cxx_1_1helpers_1_1ByteArrayOutputStream" ],
        [ "ByteBuffer", "classlog4cxx_1_1helpers_1_1ByteBuffer.html", "classlog4cxx_1_1helpers_1_1ByteBuffer" ],
        [ "CharMessageBuffer", "classlog4cxx_1_1helpers_1_1CharMessageBuffer.html", "classlog4cxx_1_1helpers_1_1CharMessageBuffer" ],
        [ "CharsetDecoder", "classlog4cxx_1_1helpers_1_1CharsetDecoder.html", "classlog4cxx_1_1helpers_1_1CharsetDecoder" ],
        [ "CharsetEncoder", "classlog4cxx_1_1helpers_1_1CharsetEncoder.html", "classlog4cxx_1_1helpers_1_1CharsetEncoder" ],
        [ "Class", "classlog4cxx_1_1helpers_1_1Class.html", "classlog4cxx_1_1helpers_1_1Class" ],
        [ "ClassNotFoundException", "classlog4cxx_1_1helpers_1_1ClassNotFoundException.html", "classlog4cxx_1_1helpers_1_1ClassNotFoundException" ],
        [ "ClassRegistration", "classlog4cxx_1_1helpers_1_1ClassRegistration.html", "classlog4cxx_1_1helpers_1_1ClassRegistration" ],
        [ "ClosedChannelException", "classlog4cxx_1_1helpers_1_1ClosedChannelException.html", "classlog4cxx_1_1helpers_1_1ClosedChannelException" ],
        [ "ConnectException", "classlog4cxx_1_1helpers_1_1ConnectException.html", "classlog4cxx_1_1helpers_1_1ConnectException" ],
        [ "CyclicBuffer", "classlog4cxx_1_1helpers_1_1CyclicBuffer.html", "classlog4cxx_1_1helpers_1_1CyclicBuffer" ],
        [ "DatagramPacket", "classlog4cxx_1_1helpers_1_1DatagramPacket.html", "classlog4cxx_1_1helpers_1_1DatagramPacket" ],
        [ "DatagramSocket", "classlog4cxx_1_1helpers_1_1DatagramSocket.html", "classlog4cxx_1_1helpers_1_1DatagramSocket" ],
        [ "Date", "classlog4cxx_1_1helpers_1_1Date.html", "classlog4cxx_1_1helpers_1_1Date" ],
        [ "DateFormat", "classlog4cxx_1_1helpers_1_1DateFormat.html", "classlog4cxx_1_1helpers_1_1DateFormat" ],
        [ "DateTimeDateFormat", "classlog4cxx_1_1helpers_1_1DateTimeDateFormat.html", "classlog4cxx_1_1helpers_1_1DateTimeDateFormat" ],
        [ "DOMException", "classlog4cxx_1_1helpers_1_1DOMException.html", "classlog4cxx_1_1helpers_1_1DOMException" ],
        [ "Exception", "classlog4cxx_1_1helpers_1_1Exception.html", "classlog4cxx_1_1helpers_1_1Exception" ],
        [ "FileInputStream", "classlog4cxx_1_1helpers_1_1FileInputStream.html", "classlog4cxx_1_1helpers_1_1FileInputStream" ],
        [ "FileOutputStream", "classlog4cxx_1_1helpers_1_1FileOutputStream.html", "classlog4cxx_1_1helpers_1_1FileOutputStream" ],
        [ "FileWatchdog", "classlog4cxx_1_1helpers_1_1FileWatchdog.html", "classlog4cxx_1_1helpers_1_1FileWatchdog" ],
        [ "IllegalArgumentException", "classlog4cxx_1_1helpers_1_1IllegalArgumentException.html", "classlog4cxx_1_1helpers_1_1IllegalArgumentException" ],
        [ "IllegalMonitorStateException", "classlog4cxx_1_1helpers_1_1IllegalMonitorStateException.html", "classlog4cxx_1_1helpers_1_1IllegalMonitorStateException" ],
        [ "IllegalStateException", "classlog4cxx_1_1helpers_1_1IllegalStateException.html", "classlog4cxx_1_1helpers_1_1IllegalStateException" ],
        [ "InetAddress", "classlog4cxx_1_1helpers_1_1InetAddress.html", "classlog4cxx_1_1helpers_1_1InetAddress" ],
        [ "InputStream", "classlog4cxx_1_1helpers_1_1InputStream.html", "classlog4cxx_1_1helpers_1_1InputStream" ],
        [ "InputStreamReader", "classlog4cxx_1_1helpers_1_1InputStreamReader.html", "classlog4cxx_1_1helpers_1_1InputStreamReader" ],
        [ "InstantiationException", "classlog4cxx_1_1helpers_1_1InstantiationException.html", "classlog4cxx_1_1helpers_1_1InstantiationException" ],
        [ "Integer", "classlog4cxx_1_1helpers_1_1Integer.html", "classlog4cxx_1_1helpers_1_1Integer" ],
        [ "InterruptedException", "classlog4cxx_1_1helpers_1_1InterruptedException.html", "classlog4cxx_1_1helpers_1_1InterruptedException" ],
        [ "InterruptedIOException", "classlog4cxx_1_1helpers_1_1InterruptedIOException.html", "classlog4cxx_1_1helpers_1_1InterruptedIOException" ],
        [ "IOException", "classlog4cxx_1_1helpers_1_1IOException.html", "classlog4cxx_1_1helpers_1_1IOException" ],
        [ "ISO8601DateFormat", "classlog4cxx_1_1helpers_1_1ISO8601DateFormat.html", "classlog4cxx_1_1helpers_1_1ISO8601DateFormat" ],
        [ "Loader", "classlog4cxx_1_1helpers_1_1Loader.html", null ],
        [ "Locale", "classlog4cxx_1_1helpers_1_1Locale.html", "classlog4cxx_1_1helpers_1_1Locale" ],
        [ "LogLog", "classlog4cxx_1_1helpers_1_1LogLog.html", "classlog4cxx_1_1helpers_1_1LogLog" ],
        [ "MessageBuffer", "classlog4cxx_1_1helpers_1_1MessageBuffer.html", "classlog4cxx_1_1helpers_1_1MessageBuffer" ],
        [ "MissingResourceException", "classlog4cxx_1_1helpers_1_1MissingResourceException.html", "classlog4cxx_1_1helpers_1_1MissingResourceException" ],
        [ "NoSuchElementException", "classlog4cxx_1_1helpers_1_1NoSuchElementException.html", "classlog4cxx_1_1helpers_1_1NoSuchElementException" ],
        [ "NullPointerException", "classlog4cxx_1_1helpers_1_1NullPointerException.html", "classlog4cxx_1_1helpers_1_1NullPointerException" ],
        [ "Object", "classlog4cxx_1_1helpers_1_1Object.html", "classlog4cxx_1_1helpers_1_1Object" ],
        [ "OnlyOnceErrorHandler", "classlog4cxx_1_1helpers_1_1OnlyOnceErrorHandler.html", "classlog4cxx_1_1helpers_1_1OnlyOnceErrorHandler" ],
        [ "OptionConverter", "classlog4cxx_1_1helpers_1_1OptionConverter.html", null ],
        [ "OutputStream", "classlog4cxx_1_1helpers_1_1OutputStream.html", "classlog4cxx_1_1helpers_1_1OutputStream" ],
        [ "OutputStreamWriter", "classlog4cxx_1_1helpers_1_1OutputStreamWriter.html", "classlog4cxx_1_1helpers_1_1OutputStreamWriter" ],
        [ "Pool", "classlog4cxx_1_1helpers_1_1Pool.html", "classlog4cxx_1_1helpers_1_1Pool" ],
        [ "PoolException", "classlog4cxx_1_1helpers_1_1PoolException.html", "classlog4cxx_1_1helpers_1_1PoolException" ],
        [ "Properties", "classlog4cxx_1_1helpers_1_1Properties.html", "classlog4cxx_1_1helpers_1_1Properties" ],
        [ "PropertyResourceBundle", "classlog4cxx_1_1helpers_1_1PropertyResourceBundle.html", "classlog4cxx_1_1helpers_1_1PropertyResourceBundle" ],
        [ "Reader", "classlog4cxx_1_1helpers_1_1Reader.html", "classlog4cxx_1_1helpers_1_1Reader" ],
        [ "RelativeTimeDateFormat", "classlog4cxx_1_1helpers_1_1RelativeTimeDateFormat.html", "classlog4cxx_1_1helpers_1_1RelativeTimeDateFormat" ],
        [ "ResourceBundle", "classlog4cxx_1_1helpers_1_1ResourceBundle.html", "classlog4cxx_1_1helpers_1_1ResourceBundle" ],
        [ "RuntimeException", "classlog4cxx_1_1helpers_1_1RuntimeException.html", "classlog4cxx_1_1helpers_1_1RuntimeException" ],
        [ "ServerSocket", "classlog4cxx_1_1helpers_1_1ServerSocket.html", "classlog4cxx_1_1helpers_1_1ServerSocket" ],
        [ "SimpleDateFormat", "classlog4cxx_1_1helpers_1_1SimpleDateFormat.html", "classlog4cxx_1_1helpers_1_1SimpleDateFormat" ],
        [ "Socket", "classlog4cxx_1_1helpers_1_1Socket.html", "classlog4cxx_1_1helpers_1_1Socket" ],
        [ "SocketException", "classlog4cxx_1_1helpers_1_1SocketException.html", "classlog4cxx_1_1helpers_1_1SocketException" ],
        [ "SocketOutputStream", "classlog4cxx_1_1helpers_1_1SocketOutputStream.html", "classlog4cxx_1_1helpers_1_1SocketOutputStream" ],
        [ "SocketTimeoutException", "classlog4cxx_1_1helpers_1_1SocketTimeoutException.html", "classlog4cxx_1_1helpers_1_1SocketTimeoutException" ],
        [ "StrftimeDateFormat", "classlog4cxx_1_1helpers_1_1StrftimeDateFormat.html", "classlog4cxx_1_1helpers_1_1StrftimeDateFormat" ],
        [ "StrictMath", "classlog4cxx_1_1helpers_1_1StrictMath.html", null ],
        [ "StringHelper", "classlog4cxx_1_1helpers_1_1StringHelper.html", null ],
        [ "StringTokenizer", "classlog4cxx_1_1helpers_1_1StringTokenizer.html", "classlog4cxx_1_1helpers_1_1StringTokenizer" ],
        [ "SyslogWriter", "classlog4cxx_1_1helpers_1_1SyslogWriter.html", "classlog4cxx_1_1helpers_1_1SyslogWriter" ],
        [ "System", "classlog4cxx_1_1helpers_1_1System.html", null ],
        [ "SystemErrWriter", "classlog4cxx_1_1helpers_1_1SystemErrWriter.html", "classlog4cxx_1_1helpers_1_1SystemErrWriter" ],
        [ "SystemOutWriter", "classlog4cxx_1_1helpers_1_1SystemOutWriter.html", "classlog4cxx_1_1helpers_1_1SystemOutWriter" ],
        [ "ThreadException", "classlog4cxx_1_1helpers_1_1ThreadException.html", "classlog4cxx_1_1helpers_1_1ThreadException" ],
        [ "ThreadLocal", "classlog4cxx_1_1helpers_1_1ThreadLocal.html", "classlog4cxx_1_1helpers_1_1ThreadLocal" ],
        [ "ThreadSpecificData", "classlog4cxx_1_1helpers_1_1ThreadSpecificData.html", "classlog4cxx_1_1helpers_1_1ThreadSpecificData" ],
        [ "ThreadUtility", "classlog4cxx_1_1helpers_1_1ThreadUtility.html", "classlog4cxx_1_1helpers_1_1ThreadUtility" ],
        [ "TimeZone", "classlog4cxx_1_1helpers_1_1TimeZone.html", "classlog4cxx_1_1helpers_1_1TimeZone" ],
        [ "Transcoder", "classlog4cxx_1_1helpers_1_1Transcoder.html", null ],
        [ "TranscoderException", "classlog4cxx_1_1helpers_1_1TranscoderException.html", "classlog4cxx_1_1helpers_1_1TranscoderException" ],
        [ "Transform", "classlog4cxx_1_1helpers_1_1Transform.html", null ],
        [ "UniCharMessageBuffer", "classlog4cxx_1_1helpers_1_1UniCharMessageBuffer.html", "classlog4cxx_1_1helpers_1_1UniCharMessageBuffer" ],
        [ "UnknownHostException", "classlog4cxx_1_1helpers_1_1UnknownHostException.html", "classlog4cxx_1_1helpers_1_1UnknownHostException" ],
        [ "WideLife", "classlog4cxx_1_1helpers_1_1WideLife.html", "classlog4cxx_1_1helpers_1_1WideLife" ],
        [ "WideMessageBuffer", "classlog4cxx_1_1helpers_1_1WideMessageBuffer.html", "classlog4cxx_1_1helpers_1_1WideMessageBuffer" ],
        [ "Writer", "classlog4cxx_1_1helpers_1_1Writer.html", "classlog4cxx_1_1helpers_1_1Writer" ],
        [ "XMLDOMDocument", "classlog4cxx_1_1helpers_1_1XMLDOMDocument.html", "classlog4cxx_1_1helpers_1_1XMLDOMDocument" ],
        [ "XMLDOMElement", "classlog4cxx_1_1helpers_1_1XMLDOMElement.html", "classlog4cxx_1_1helpers_1_1XMLDOMElement" ],
        [ "XMLDOMNode", "classlog4cxx_1_1helpers_1_1XMLDOMNode.html", "classlog4cxx_1_1helpers_1_1XMLDOMNode" ],
        [ "XMLDOMNodeList", "classlog4cxx_1_1helpers_1_1XMLDOMNodeList.html", "classlog4cxx_1_1helpers_1_1XMLDOMNodeList" ]
      ] ],
      [ "net", "namespacelog4cxx_1_1net.html", [
        [ "SMTPAppender", "classlog4cxx_1_1net_1_1SMTPAppender.html", "classlog4cxx_1_1net_1_1SMTPAppender" ],
        [ "SocketAppenderSkeleton", "classlog4cxx_1_1net_1_1SocketAppenderSkeleton.html", "classlog4cxx_1_1net_1_1SocketAppenderSkeleton" ],
        [ "SyslogAppender", "classlog4cxx_1_1net_1_1SyslogAppender.html", "classlog4cxx_1_1net_1_1SyslogAppender" ],
        [ "TelnetAppender", "classlog4cxx_1_1net_1_1TelnetAppender.html", "classlog4cxx_1_1net_1_1TelnetAppender" ],
        [ "XMLSocketAppender", "classlog4cxx_1_1net_1_1XMLSocketAppender.html", "classlog4cxx_1_1net_1_1XMLSocketAppender" ]
      ] ],
      [ "nt", "namespacelog4cxx_1_1nt.html", [
        [ "NTEventLogAppender", "classlog4cxx_1_1nt_1_1NTEventLogAppender.html", "classlog4cxx_1_1nt_1_1NTEventLogAppender" ],
        [ "OutputDebugStringAppender", "classlog4cxx_1_1nt_1_1OutputDebugStringAppender.html", "classlog4cxx_1_1nt_1_1OutputDebugStringAppender" ]
      ] ],
      [ "pattern", "namespacelog4cxx_1_1pattern.html", [
        [ "CachedDateFormat", "classlog4cxx_1_1pattern_1_1CachedDateFormat.html", "classlog4cxx_1_1pattern_1_1CachedDateFormat" ],
        [ "ClassNamePatternConverter", "classlog4cxx_1_1pattern_1_1ClassNamePatternConverter.html", "classlog4cxx_1_1pattern_1_1ClassNamePatternConverter" ],
        [ "ColorEndPatternConverter", "classlog4cxx_1_1pattern_1_1ColorEndPatternConverter.html", "classlog4cxx_1_1pattern_1_1ColorEndPatternConverter" ],
        [ "ColorStartPatternConverter", "classlog4cxx_1_1pattern_1_1ColorStartPatternConverter.html", "classlog4cxx_1_1pattern_1_1ColorStartPatternConverter" ],
        [ "DatePatternConverter", "classlog4cxx_1_1pattern_1_1DatePatternConverter.html", "classlog4cxx_1_1pattern_1_1DatePatternConverter" ],
        [ "FileDatePatternConverter", "classlog4cxx_1_1pattern_1_1FileDatePatternConverter.html", null ],
        [ "FileLocationPatternConverter", "classlog4cxx_1_1pattern_1_1FileLocationPatternConverter.html", "classlog4cxx_1_1pattern_1_1FileLocationPatternConverter" ],
        [ "FormattingInfo", "classlog4cxx_1_1pattern_1_1FormattingInfo.html", "classlog4cxx_1_1pattern_1_1FormattingInfo" ],
        [ "FullLocationPatternConverter", "classlog4cxx_1_1pattern_1_1FullLocationPatternConverter.html", "classlog4cxx_1_1pattern_1_1FullLocationPatternConverter" ],
        [ "IntegerPatternConverter", "classlog4cxx_1_1pattern_1_1IntegerPatternConverter.html", "classlog4cxx_1_1pattern_1_1IntegerPatternConverter" ],
        [ "LevelPatternConverter", "classlog4cxx_1_1pattern_1_1LevelPatternConverter.html", "classlog4cxx_1_1pattern_1_1LevelPatternConverter" ],
        [ "LineLocationPatternConverter", "classlog4cxx_1_1pattern_1_1LineLocationPatternConverter.html", "classlog4cxx_1_1pattern_1_1LineLocationPatternConverter" ],
        [ "LineSeparatorPatternConverter", "classlog4cxx_1_1pattern_1_1LineSeparatorPatternConverter.html", "classlog4cxx_1_1pattern_1_1LineSeparatorPatternConverter" ],
        [ "LiteralPatternConverter", "classlog4cxx_1_1pattern_1_1LiteralPatternConverter.html", "classlog4cxx_1_1pattern_1_1LiteralPatternConverter" ],
        [ "LoggerPatternConverter", "classlog4cxx_1_1pattern_1_1LoggerPatternConverter.html", "classlog4cxx_1_1pattern_1_1LoggerPatternConverter" ],
        [ "LoggingEventPatternConverter", "classlog4cxx_1_1pattern_1_1LoggingEventPatternConverter.html", "classlog4cxx_1_1pattern_1_1LoggingEventPatternConverter" ],
        [ "MDCPatternConverter", "classlog4cxx_1_1pattern_1_1MDCPatternConverter.html", "classlog4cxx_1_1pattern_1_1MDCPatternConverter" ],
        [ "MessagePatternConverter", "classlog4cxx_1_1pattern_1_1MessagePatternConverter.html", "classlog4cxx_1_1pattern_1_1MessagePatternConverter" ],
        [ "MethodLocationPatternConverter", "classlog4cxx_1_1pattern_1_1MethodLocationPatternConverter.html", "classlog4cxx_1_1pattern_1_1MethodLocationPatternConverter" ],
        [ "NameAbbreviator", "classlog4cxx_1_1pattern_1_1NameAbbreviator.html", "classlog4cxx_1_1pattern_1_1NameAbbreviator" ],
        [ "NamePatternConverter", "classlog4cxx_1_1pattern_1_1NamePatternConverter.html", "classlog4cxx_1_1pattern_1_1NamePatternConverter" ],
        [ "NDCPatternConverter", "classlog4cxx_1_1pattern_1_1NDCPatternConverter.html", "classlog4cxx_1_1pattern_1_1NDCPatternConverter" ],
        [ "PatternConverter", "classlog4cxx_1_1pattern_1_1PatternConverter.html", "classlog4cxx_1_1pattern_1_1PatternConverter" ],
        [ "PatternParser", "classlog4cxx_1_1pattern_1_1PatternParser.html", null ],
        [ "PropertiesPatternConverter", "classlog4cxx_1_1pattern_1_1PropertiesPatternConverter.html", "classlog4cxx_1_1pattern_1_1PropertiesPatternConverter" ],
        [ "RelativeTimePatternConverter", "classlog4cxx_1_1pattern_1_1RelativeTimePatternConverter.html", "classlog4cxx_1_1pattern_1_1RelativeTimePatternConverter" ],
        [ "ShortFileLocationPatternConverter", "classlog4cxx_1_1pattern_1_1ShortFileLocationPatternConverter.html", "classlog4cxx_1_1pattern_1_1ShortFileLocationPatternConverter" ],
        [ "ThreadPatternConverter", "classlog4cxx_1_1pattern_1_1ThreadPatternConverter.html", "classlog4cxx_1_1pattern_1_1ThreadPatternConverter" ],
        [ "ThreadUsernamePatternConverter", "classlog4cxx_1_1pattern_1_1ThreadUsernamePatternConverter.html", "classlog4cxx_1_1pattern_1_1ThreadUsernamePatternConverter" ],
        [ "ThrowableInformationPatternConverter", "classlog4cxx_1_1pattern_1_1ThrowableInformationPatternConverter.html", "classlog4cxx_1_1pattern_1_1ThrowableInformationPatternConverter" ]
      ] ],
      [ "qt", "namespacelog4cxx_1_1qt.html", [
        [ "Configuration", "classlog4cxx_1_1qt_1_1Configuration.html", null ]
      ] ],
      [ "rolling", "namespacelog4cxx_1_1rolling.html", [
        [ "Action", "classlog4cxx_1_1rolling_1_1Action.html", "classlog4cxx_1_1rolling_1_1Action" ],
        [ "FileRenameAction", "classlog4cxx_1_1rolling_1_1FileRenameAction.html", "classlog4cxx_1_1rolling_1_1FileRenameAction" ],
        [ "FilterBasedTriggeringPolicy", "classlog4cxx_1_1rolling_1_1FilterBasedTriggeringPolicy.html", "classlog4cxx_1_1rolling_1_1FilterBasedTriggeringPolicy" ],
        [ "FixedWindowRollingPolicy", "classlog4cxx_1_1rolling_1_1FixedWindowRollingPolicy.html", "classlog4cxx_1_1rolling_1_1FixedWindowRollingPolicy" ],
        [ "GZCompressAction", "classlog4cxx_1_1rolling_1_1GZCompressAction.html", "classlog4cxx_1_1rolling_1_1GZCompressAction" ],
        [ "ManualTriggeringPolicy", "classlog4cxx_1_1rolling_1_1ManualTriggeringPolicy.html", "classlog4cxx_1_1rolling_1_1ManualTriggeringPolicy" ],
        [ "MultiprocessRollingFileAppender", "classlog4cxx_1_1rolling_1_1MultiprocessRollingFileAppender.html", "classlog4cxx_1_1rolling_1_1MultiprocessRollingFileAppender" ],
        [ "RollingFileAppender", "classlog4cxx_1_1rolling_1_1RollingFileAppender.html", "classlog4cxx_1_1rolling_1_1RollingFileAppender" ],
        [ "RollingPolicy", "classlog4cxx_1_1rolling_1_1RollingPolicy.html", "classlog4cxx_1_1rolling_1_1RollingPolicy" ],
        [ "RollingPolicyBase", "classlog4cxx_1_1rolling_1_1RollingPolicyBase.html", "classlog4cxx_1_1rolling_1_1RollingPolicyBase" ],
        [ "RolloverDescription", "classlog4cxx_1_1rolling_1_1RolloverDescription.html", "classlog4cxx_1_1rolling_1_1RolloverDescription" ],
        [ "SizeBasedTriggeringPolicy", "classlog4cxx_1_1rolling_1_1SizeBasedTriggeringPolicy.html", "classlog4cxx_1_1rolling_1_1SizeBasedTriggeringPolicy" ],
        [ "TimeBasedRollingPolicy", "classlog4cxx_1_1rolling_1_1TimeBasedRollingPolicy.html", "classlog4cxx_1_1rolling_1_1TimeBasedRollingPolicy" ],
        [ "TriggeringPolicy", "classlog4cxx_1_1rolling_1_1TriggeringPolicy.html", "classlog4cxx_1_1rolling_1_1TriggeringPolicy" ],
        [ "ZipCompressAction", "classlog4cxx_1_1rolling_1_1ZipCompressAction.html", "classlog4cxx_1_1rolling_1_1ZipCompressAction" ]
      ] ],
      [ "spi", "namespacelog4cxx_1_1spi.html", [
        [ "AppenderAttachable", "classlog4cxx_1_1spi_1_1AppenderAttachable.html", "classlog4cxx_1_1spi_1_1AppenderAttachable" ],
        [ "Configurator", "classlog4cxx_1_1spi_1_1Configurator.html", "classlog4cxx_1_1spi_1_1Configurator" ],
        [ "DefaultRepositorySelector", "classlog4cxx_1_1spi_1_1DefaultRepositorySelector.html", "classlog4cxx_1_1spi_1_1DefaultRepositorySelector" ],
        [ "ErrorCode", "classlog4cxx_1_1spi_1_1ErrorCode.html", null ],
        [ "ErrorHandler", "classlog4cxx_1_1spi_1_1ErrorHandler.html", "classlog4cxx_1_1spi_1_1ErrorHandler" ],
        [ "Filter", "classlog4cxx_1_1spi_1_1Filter.html", "classlog4cxx_1_1spi_1_1Filter" ],
        [ "HierarchyEventListener", "classlog4cxx_1_1spi_1_1HierarchyEventListener.html", "classlog4cxx_1_1spi_1_1HierarchyEventListener" ],
        [ "LocationInfo", "classlog4cxx_1_1spi_1_1LocationInfo.html", "classlog4cxx_1_1spi_1_1LocationInfo" ],
        [ "LoggerFactory", "classlog4cxx_1_1spi_1_1LoggerFactory.html", "classlog4cxx_1_1spi_1_1LoggerFactory" ],
        [ "LoggerRepository", "classlog4cxx_1_1spi_1_1LoggerRepository.html", "classlog4cxx_1_1spi_1_1LoggerRepository" ],
        [ "LoggingEvent", "classlog4cxx_1_1spi_1_1LoggingEvent.html", "classlog4cxx_1_1spi_1_1LoggingEvent" ],
        [ "OptionHandler", "classlog4cxx_1_1spi_1_1OptionHandler.html", "classlog4cxx_1_1spi_1_1OptionHandler" ],
        [ "RepositorySelector", "classlog4cxx_1_1spi_1_1RepositorySelector.html", "classlog4cxx_1_1spi_1_1RepositorySelector" ],
        [ "RootLogger", "classlog4cxx_1_1spi_1_1RootLogger.html", "classlog4cxx_1_1spi_1_1RootLogger" ],
        [ "TriggeringEventEvaluator", "classlog4cxx_1_1spi_1_1TriggeringEventEvaluator.html", "classlog4cxx_1_1spi_1_1TriggeringEventEvaluator" ]
      ] ],
      [ "varia", "namespacelog4cxx_1_1varia.html", [
        [ "FallbackErrorHandler", "classlog4cxx_1_1varia_1_1FallbackErrorHandler.html", "classlog4cxx_1_1varia_1_1FallbackErrorHandler" ]
      ] ],
      [ "xml", "namespacelog4cxx_1_1xml.html", [
        [ "DOMConfigurator", "classlog4cxx_1_1xml_1_1DOMConfigurator.html", "classlog4cxx_1_1xml_1_1DOMConfigurator" ],
        [ "XMLLayout", "classlog4cxx_1_1xml_1_1XMLLayout.html", "classlog4cxx_1_1xml_1_1XMLLayout" ]
      ] ],
      [ "Appender", "classlog4cxx_1_1Appender.html", "classlog4cxx_1_1Appender" ],
      [ "AppenderSkeleton", "classlog4cxx_1_1AppenderSkeleton.html", "classlog4cxx_1_1AppenderSkeleton" ],
      [ "AsyncAppender", "classlog4cxx_1_1AsyncAppender.html", "classlog4cxx_1_1AsyncAppender" ],
      [ "BasicConfigurator", "classlog4cxx_1_1BasicConfigurator.html", "classlog4cxx_1_1BasicConfigurator" ],
      [ "ConsoleAppender", "classlog4cxx_1_1ConsoleAppender.html", "classlog4cxx_1_1ConsoleAppender" ],
      [ "DefaultConfigurator", "classlog4cxx_1_1DefaultConfigurator.html", null ],
      [ "DefaultLoggerFactory", "classlog4cxx_1_1DefaultLoggerFactory.html", "classlog4cxx_1_1DefaultLoggerFactory" ],
      [ "File", "classlog4cxx_1_1File.html", "classlog4cxx_1_1File" ],
      [ "FileAppender", "classlog4cxx_1_1FileAppender.html", "classlog4cxx_1_1FileAppender" ],
      [ "FMTLayout", "classlog4cxx_1_1FMTLayout.html", "classlog4cxx_1_1FMTLayout" ],
      [ "Hierarchy", "classlog4cxx_1_1Hierarchy.html", "classlog4cxx_1_1Hierarchy" ],
      [ "HTMLLayout", "classlog4cxx_1_1HTMLLayout.html", "classlog4cxx_1_1HTMLLayout" ],
      [ "JSONLayout", "classlog4cxx_1_1JSONLayout.html", "classlog4cxx_1_1JSONLayout" ],
      [ "Layout", "classlog4cxx_1_1Layout.html", "classlog4cxx_1_1Layout" ],
      [ "Level", "classlog4cxx_1_1Level.html", "classlog4cxx_1_1Level" ],
      [ "LevelChange", "classlog4cxx_1_1LevelChange.html", "classlog4cxx_1_1LevelChange" ],
      [ "Logger", "classlog4cxx_1_1Logger.html", "classlog4cxx_1_1Logger" ],
      [ "LoggerInstancePtr", "classlog4cxx_1_1LoggerInstancePtr.html", "classlog4cxx_1_1LoggerInstancePtr" ],
      [ "LogManager", "classlog4cxx_1_1LogManager.html", null ],
      [ "logstream", "classlog4cxx_1_1logstream.html", "classlog4cxx_1_1logstream" ],
      [ "logstream_base", "classlog4cxx_1_1logstream__base.html", "classlog4cxx_1_1logstream__base" ],
      [ "MDC", "classlog4cxx_1_1MDC.html", "classlog4cxx_1_1MDC" ],
      [ "NDC", "classlog4cxx_1_1NDC.html", "classlog4cxx_1_1NDC" ],
      [ "Optional", "classlog4cxx_1_1Optional.html", "classlog4cxx_1_1Optional" ],
      [ "PatternLayout", "classlog4cxx_1_1PatternLayout.html", "classlog4cxx_1_1PatternLayout" ],
      [ "PropertyConfigurator", "classlog4cxx_1_1PropertyConfigurator.html", "classlog4cxx_1_1PropertyConfigurator" ],
      [ "SimpleLayout", "classlog4cxx_1_1SimpleLayout.html", "classlog4cxx_1_1SimpleLayout" ],
      [ "ulogstream", "classlog4cxx_1_1ulogstream.html", "classlog4cxx_1_1ulogstream" ],
      [ "wlogstream", "classlog4cxx_1_1wlogstream.html", "classlog4cxx_1_1wlogstream" ],
      [ "WriterAppender", "classlog4cxx_1_1WriterAppender.html", "classlog4cxx_1_1WriterAppender" ]
    ] ]
];